/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Charly Cimino
 */
import Negocio.ProductoNegocio;
import Modelo.Producto;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class ListaPanel extends javax.swing.JPanel {
    
    private ProductoPanel productoPanel;
    private ProductoNegocio negocio;
    private DefaultTableModel modelo;
    
    /**
     * Creates new form ListaPanel
     */
    public ListaPanel(ProductoNegocio negocio,ProductoPanel productoPanel) {
        this.negocio = negocio;
        this.productoPanel=productoPanel;
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProductos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        ListaProductos.setBackground(new java.awt.Color(204, 204, 204));
        ListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Nombre", "Categoria", "Cantidad", "Precio", "Disponible"
            }
        ));
        jScrollPane1.setViewportView(ListaProductos);

        btnEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminar.setText("Eliminar");

        btnEditar.setBackground(new java.awt.Color(255, 153, 153));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(26, 26, 26)
                .addComponent(btnEliminar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar))
                .addGap(0, 8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
      int fila =ListaProductos.getSelectedRow();
      if (fila ==-1){
          JOptionPane.showMessageDialog(this, "Debe seleccionar una fila de la tabla para editar.");
          return;
      }
      String codigo=(String)ListaProductos.getValueAt(fila, 1);
      Producto seleccionado=negocio.getLista().stream().filter(p->p.getCodigo().equals(codigo)).findFirst().orElse(null);
      
      if (seleccionado != null){
          //cargar los datos en el registro de producto
          productoPanel.cargarProducto(seleccionado);
          JOptionPane.showMessageDialog(this, "Producto cargado en la pestaña de registro para editar\nCódigo:"+seleccionado.getCodigo());
      }
            
    }//GEN-LAST:event_btnEditarActionPerformed
//metodo para cargar la tabla
    public void cargarTabla(){
        modelo = (DefaultTableModel) ListaProductos.getModel();
        modelo.setRowCount(0);//limpia la tabla
        
        List<Producto>lista=negocio.getLista();
        int id= 1;
        
        for (Producto p:lista){
            modelo.addRow(new Object[]{
                id++,
                p.getCodigo(),
                p.getNombre(),
                p.getCategoria(),
                p.getCantidad(),
                p.getPrecio(),
                p.isDisponible()? "Sí":"No"
            });
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListaProductos;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
